name: new_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.4.1
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  file_picker: ^8.3.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  razorpay_flutter: ^1.3.7
  local_auth: ^2.3.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  local_auth_android: ^1.0.46
  animate_do: ^4.2.0
  android_intent_plus: ^5.3.0
  firebase_messaging: ^15.2.4
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  font_awesome_flutter: ^10.8.0
  google_mlkit_text_recognition: ^0.14.0
  animated_icon_button: ^1.0.2
  animated_toggle_switch: ^0.8.4
  flutter_emoji_feedback: ^1.0.3
  geolocator: ^13.0.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.11.0
  provider: ^6.1.2
  intl: ^0.18.0
  lottie: ^3.3.1
  just_audio: ^0.9.18
  fluttertoast: ^8.2.0
  syncfusion_flutter_gauges: ^20.4.41
  pdf: ^3.11.3
  printing: ^5.11.1
  uuid: ^4.0.0
  flutter_bluetooth_serial: ^0.4.0
  open_filex: ^4.3.2
  device_info_plus: ^11.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  video_player: ^2.9.5
  chewie: ^1.11.1
  animated_text_kit: ^4.2.3
  flutter_tts: ^3.8.5
  http: ^1.2.0
  flutter_osm_plugin: ^1.3.6
  flutter_polyline_points: ^2.1.0
  google_ml_kit: ^0.19.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/main_logo.png"

flutter_native_splash:
  color: "#000000"  # Black background
  image: "assets/images/splash.png"  # Ensure this image exists
  android_12:
    color: "#000000"  # Black background for Android 12+
    image: "assets/images/splash.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/car.png
   - assets/images/contact_us.png
   - assets/images/blank.jpeg
   - assets/images/terms_and_conditions.png
   - assets/images/terms.png
   - assets/icons/google_icon.png
   - assets/images/login.png
   - assets/images/signup.png
   - assets/images/user.png
   - assets/images/car_details.png
   - assets/images/shlok.jpg
   - assets/images/tirrth.jpg
   - assets/images/vian.jpg
   - assets/images/sharyu_maam.png
   - assets/images/toll.jpg
   - assets/images/password.png
   - assets/images/change_password.png
   - assets/images/edit_profile.png
   - assets/images/change_email.png
   - assets/images/assitance.png
   - assets/images/violation.png
   - assets/images/no_notification1.png
   - assets/images/Wallet_Pic.png
   - assets/images/no_notify_1.jpg
   - assets/images/blue_tick.png
   - assets/images/no_payments.jpg
   - assets/images/main_logo.png
   - assets/images/main_logo_2.png
   - assets/images/splash.png
   - assets/images/Start1.png
   - assets/images/Start2.png
   - assets/images/Start3.png
   - assets/images/how_it_works_1.png
   - assets/images/how_it_works_2.png
   - assets/images/how_it_works_3.png
   - assets/images/how_it_works_4.png
   - assets/images/how_it_works_5.png
   - assets/images/road_background.png
   - assets/images/toll_plaza.png
   - assets/images/toll_animation.mp4
   - assets/images/Car/Mercedes-Benz/S-Class/White.png
   - assets/images/Car/Mercedes-Benz/S-Class/Grey.png
   - assets/images/Car/Mercedes-Benz/S-Class/Blue.png
   - assets/images/Car/Mercedes-Benz/C-Class/White.png
   - assets/images/Car/Mercedes-Benz/C-Class/Red.png
   - assets/images/Car/Mercedes-Benz/C-Class/Brown.png
   - assets/images/Car/Mercedes-Benz/GLS/White.png
   - assets/images/Car/Mercedes-Benz/GLS/Brown.png
   - assets/images/Car/Mercedes-Benz/GLS/Green.png
   - assets/images/Car/Honda/City/Grey.png
   - assets/images/Car/Honda/City/Red.png
   - assets/images/Car/Honda/City/White.png
   - assets/images/Car/Honda/Amaze/Black.png
   - assets/images/Car/Honda/Amaze/Red.png
   - assets/images/Car/Honda/Amaze/White.png
   - assets/images/Car/Honda/Elevate/Blue.png
   - assets/images/Car/Honda/Elevate/Orange.png
   - assets/images/Car/Honda/Elevate/Brown.png
   - assets/images/Car/Hyundai/Creta/Brown.png
   - assets/images/Car/Hyundai/Creta/Orange.png
   - assets/images/Car/Hyundai/Creta/Red.png
   - assets/images/Car/Hyundai/Creta/White.png
   - assets/images/Car/Hyundai/Venue/Blue.png
   - assets/images/Car/Hyundai/Venue/Green.png
   - assets/images/Car/Hyundai/Venue/Grey.png
   - assets/images/Car/Mahindra/Scorpio/Black.png
   - assets/images/Car/Mahindra/Scorpio/Silver.png
   - assets/images/Car/Mahindra/Scorpio/White.png
   - assets/images/Car/Mahindra/XUV-700/Black.png
   - assets/images/Car/Mahindra/XUV-700/Blue.png
   - assets/images/Car/Mahindra/XUV-700/Orange.png
   - assets/images/Car/Maruti-Suzuki/Brezza/Green.png
   - assets/images/Car/Maruti-Suzuki/Brezza/Red.png
   - assets/images/Car/Maruti-Suzuki/Brezza/White.png
   - assets/images/Car/Maruti-Suzuki/Dzire/Brown.png
   - assets/images/Car/Maruti-Suzuki/Dzire/Red.png
   - assets/images/Car/Maruti-Suzuki/Dzire/Silver.png
   - assets/images/Car/Maruti-Suzuki/Dzire/White.png
   - assets/images/Car/Maruti-Suzuki/Wagon-R/Orange.png
   - assets/images/Car/Maruti-Suzuki/Wagon-R/Red.png
   - assets/images/Car/Maruti-Suzuki/Wagon-R/White.png
   - assets/images/Car/Mg/Gloster/Black.png
   - assets/images/Car/Mg/Gloster/Brown.png
   - assets/images/Car/Mg/Gloster/Red.png
   - assets/images/Car/Mg/Hector/Grey.png
   - assets/images/Car/Mg/Hector/White.png
   - assets/images/Car/Mg/Hector/Red.png
   - assets/images/Car/Mg/Zs-Ev/Blue.png
   - assets/images/Car/Mg/Zs-Ev/White.png
   - assets/images/Car/Mg/Zs-Ev/Red.png
   - assets/images/Car/Tata/Curvv/Blue.png
   - assets/images/Car/Tata/Curvv/Brown.png
   - assets/images/Car/Tata/Curvv/Red.png
   - assets/images/Car/Tata/Nexon/Blue.png
   - assets/images/Car/Tata/Nexon/Green.png
   - assets/images/Car/Tata/Nexon/Purple.png
   - assets/images/Car/Tata/Nexon/Red.png
   - assets/images/Car/Tata/Harrier/Red.png
   - assets/images/Car/Tata/Harrier/Grey.png
   - assets/images/Car/Tata/Harrier/Yellow.png
   - assets/images/Car/Toyota/Fortuner/White.png
   - assets/images/Car/Toyota/Fortuner/Grey.png
   - assets/images/Car/Toyota/Fortuner/Red.png
   - assets/images/Car/Toyota/Innova/Blue.png
   - assets/images/Car/Toyota/Innova/Grey.png
   - assets/images/Car/Toyota/Innova/Silver.png
   - assets/images/Car/Volkswagen/Tiguan/White.png
   - assets/images/Car/Volkswagen/Tiguan/Blue.png
   - assets/images/Car/Volkswagen/Tiguan/Red.png
   - assets/images/Car/Volkswagen/Taigun/Blue.png
   - assets/images/Car/Volkswagen/Taigun/White.png
   - assets/images/Car/Volkswagen/Taigun/Yellow.png
   - assets/images/Car/Volkswagen/Virtus/Blue.png
   - assets/images/Car/Volkswagen/Virtus/Red.png
   - assets/images/Car/Volkswagen/Virtus/White.png
   - assets/images/Car/Skoda/Kushaq/Orange.png
   - assets/images/Car/Skoda/Kushaq/Red.png
   - assets/images/Car/Skoda/Kushaq/White.png
   - assets/images/Car/Skoda/Slavia/Blue.png
   - assets/images/Car/Skoda/Slavia/Red.png
   - assets/images/Car/Skoda/Slavia/Silver.png
   - assets/images/Car/Skoda/Kodiaq/Green.png
   - assets/images/Car/Skoda/Kodiaq/Blue.png
   - assets/images/Car/Skoda/Kodiaq/Grey.png



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "#" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: DancingScript
     fonts:
     - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
