// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy_54DbR9ugkYFoaadFeAD8SJf_b07P9I',
    appId: '1:1091734142267:web:be8ebe9f6dba3f03878b1e',
    messagingSenderId: '1091734142267',
    projectId: 'fir-demo-95959',
    authDomain: 'fir-demo-95959.firebaseapp.com',
    storageBucket: 'fir-demo-95959.firebasestorage.app',
    measurementId: 'G-G8K0H7J9FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19YEg4DKlPUZYVFO23Y6zkDq2V8Ab2a0',
    appId: '1:1091734142267:android:a027f14a54635695878b1e',
    messagingSenderId: '1091734142267',
    projectId: 'fir-demo-95959',
    storageBucket: 'fir-demo-95959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgVVTks4foEPU-aaJWb1WZDYbJMhLhjE',
    appId: '1:1091734142267:ios:6f679a42d245a9ce878b1e',
    messagingSenderId: '1091734142267',
    projectId: 'fir-demo-95959',
    storageBucket: 'fir-demo-95959.firebasestorage.app',
    androidClientId: '1091734142267-bs706hdlcje6rppjifqgiemc9hemg28e.apps.googleusercontent.com',
    iosClientId: '1091734142267-bqv5594h06vsl2rqjr7813of0j792aml.apps.googleusercontent.com',
    iosBundleId: 'com.example.newUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgVVTks4foEPU-aaJWb1WZDYbJMhLhjE',
    appId: '1:1091734142267:ios:6f679a42d245a9ce878b1e',
    messagingSenderId: '1091734142267',
    projectId: 'fir-demo-95959',
    storageBucket: 'fir-demo-95959.firebasestorage.app',
    androidClientId: '1091734142267-bs706hdlcje6rppjifqgiemc9hemg28e.apps.googleusercontent.com',
    iosClientId: '1091734142267-bqv5594h06vsl2rqjr7813of0j792aml.apps.googleusercontent.com',
    iosBundleId: 'com.example.newUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy_54DbR9ugkYFoaadFeAD8SJf_b07P9I',
    appId: '1:1091734142267:web:477054ac34f25f07878b1e',
    messagingSenderId: '1091734142267',
    projectId: 'fir-demo-95959',
    authDomain: 'fir-demo-95959.firebaseapp.com',
    storageBucket: 'fir-demo-95959.firebasestorage.app',
    measurementId: 'G-QVG9WN0215',
  );
}
