// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEhZloP9izEVQ_9hcQIxYhxkoNTJPvmQ4',
    appId: '1:518604888058:web:3e29a29f99d43554a57643',
    messagingSenderId: '518604888058',
    projectId: 'login-f6e14',
    authDomain: 'login-f6e14.firebaseapp.com',
    storageBucket: 'login-f6e14.firebasestorage.app',
    measurementId: 'G-DD5TC09V7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDp6TFXweOP2lBVZy2BlsJDGjzXHdAIA',
    appId: '1:518604888058:android:ea3d2e65a4892a4da57643',
    messagingSenderId: '518604888058',
    projectId: 'login-f6e14',
    storageBucket: 'login-f6e14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx2B06Pu-SlRhGe4OYeFFvItJXiu29pvo',
    appId: '1:518604888058:ios:1ee2f8720872a93da57643',
    messagingSenderId: '518604888058',
    projectId: 'login-f6e14',
    storageBucket: 'login-f6e14.firebasestorage.app',
    androidClientId: '518604888058-3qctc1ef2h05ep9einthcms46tjvpjar.apps.googleusercontent.com',
    iosClientId: '518604888058-rggim8v9njsqljuom8lhh0f6q3ikl8nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx2B06Pu-SlRhGe4OYeFFvItJXiu29pvo',
    appId: '1:518604888058:ios:1ee2f8720872a93da57643',
    messagingSenderId: '518604888058',
    projectId: 'login-f6e14',
    storageBucket: 'login-f6e14.firebasestorage.app',
    androidClientId: '518604888058-3qctc1ef2h05ep9einthcms46tjvpjar.apps.googleusercontent.com',
    iosClientId: '518604888058-rggim8v9njsqljuom8lhh0f6q3ikl8nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPOd16D_D7ZuKV26_5b1rG06dJmAUYai0',
    appId: '1:518604888058:web:801d1e2df3db3ec3a57643',
    messagingSenderId: '518604888058',
    projectId: 'login-f6e14',
    authDomain: 'login-f6e14.firebaseapp.com',
    storageBucket: 'login-f6e14.firebasestorage.app',
    measurementId: 'G-20P4DZ9WGR',
  );
}
